name: "Regretaton Actions"

on:
  - push
  - schedule:
      - cron: "13 50 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install node"
        uses: actions/setup-node@v1
      - name: "Install NPM deps"
        run: npm install
      - name: "Run code"
        run: node index.js
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN }}
